baseURL = 'https://www.jangboolee.com/'
languageCode = 'en-us'
title = 'Jangboo Lee'
theme = 'PaperMod'
publishDir = "../public"

[taxonomies]
    category = 'categories'
    tag = 'tags'

[menus]
    [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
    [[menus.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
    [[menus.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[outputs]
    [outputs.home]
    home = ["HTML", "RSS", "JSON"]

[params]
    [params.homeInfoParams]
    Title = "Hi, I'm Jangboo ğŸ‘‹ TOML"
    Content = """
Welcome to my website! Here you'll find:

* ğŸƒâ€â™‚ï¸ My trail running adventures
* ğŸ’­ My reviews on products I've tested
* ğŸ”’ My thoughts and tips on data privacy
* ğŸ–¥ï¸ Projects in data science and programming

Explore from the menu or recent posts below.
    """